name: CI for all macOS commands

on: [push, pull_request]

jobs:
  test-commands:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Execute all commands
        run: |
          find ./terminal -type f -name "*.sh" -print0 | while IFS= read -r -d '' file; do
            echo "▶️ Execute $$file..."
            chmod +x "$$file"
            bash "$$file" || exit 1
            echo "✅ Success!"
          done